export enum RMQClient {
  AUTH = 'AUTH',
  USER = 'USER',
  CONTACT = 'CONTACT',
  CHAT = 'CHAT',
  AUTH_USER = 'AUTH_USER',
  CONTACT_USER = 'CONTACT_USER',
  USER_CONTACT = 'USER_CONTACT',
  UPLOAD_USER = 'UPLOAD_USER',
  CHAT_USER = 'CHAT_USER',
}

export enum RMQClientService {
  AUTH = 'AUTH_SERVICE',
  USER = 'USER_SERVICE',
  CONTACT = 'CONTACT_SERVICE',
  CHAT = 'CHAT_SERVICE',
  AUTH_USER = 'AUTH_USER_SERVICE',
  CONTACT_USER = 'CONTACT_USER_SERVICE',
  USER_CONTACT = 'USER_CONTACT_SERVICE',
  UPLOAD_USER = 'UPLOAD_USER_SERVICE',
  CHAT_USER = 'CHAT_USER_SERVICE',
}

export enum RequestMethods {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  OPTIONS = 'OPTIONS',
  HEAD = 'HEAD',
}

export enum ContactStatus {
  SENT = 'SENT',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  FRIENDS = 'FRIENDS',
  BLOCKED = 'BLOCKED',
}

export enum TokenType {
  RESET_PASSWORD = 'RESET_PASSWORD',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
}

export enum AccountRoles {
  ADMIN = 'ADMIN',
  USER = 'USER',
  MODERATOR = 'MODERATOR',
  OPERATOR = 'OPERATOR',
  MEMBER = 'MEMBER',
  MANAGER = 'MANAGER',
  SUPERVISOR = 'SUPERVISOR',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  DELETED = 'DELETED',
}
